#!/bin/bash

#black  30              normal                                  0
#red    31              bold/lighter                            1
#green  32              darker                                  2
#yellow 33              italicized                              3
#blue   34              underlined                              4
#purple 35              (indeterminate)                         5
#cyan   36              (indeterminate)                         6
#white  37              color background on prompt,             7
#                            words terminal background color
#                       transparent (disappears)                8
#                       strikethrough                           9
START_COLOR=31
END_COLOR=37
START_STYLE=0
BAD_STYLES=("5" "6" "8")
END_STYLE=9

member() {
    search_item=$1
    arr_name=$2[@]
    array=("${!arr_name}")
    for item in "${array[@]}"; do
        if [ $search_item == $item ]; then
            return 0
        fi
    done
    return 1
}

#set numbers at end to start at beginning with first one
if [ -z $CURRENT_PROMPT_COLOR_NUM ]; then
    CURRENT_PROMPT_COLOR_NUM=$END_COLOR
fi

if [ -z $CURRENT_PROMPT_TEXT_NUM ]; then
    CURRENT_PROMPT_TEXT_NUM=$END_STYLE
fi

#carry out rotation, skipping bad numbers
#color rotation
CURRENT_PROMPT_COLOR_NUM=$((CURRENT_PROMPT_COLOR_NUM + 1))
if [ $CURRENT_PROMPT_COLOR_NUM == $((END_COLOR + 1)) ]; then #beyond colors
    CURRENT_PROMPT_COLOR_NUM=$START_COLOR
    #style rotation
    CURRENT_PROMPT_TEXT_NUM=$((CURRENT_PROMPT_TEXT_NUM + 1))
    if [ $CURRENT_PROMPT_TEXT_NUM == $((END_STYLE + 1)) ]; then #beyond options
        CURRENT_PROMPT_TEXT_NUM=$START_STYLE
    fi
    while  member $CURRENT_PROMPT_TEXT_NUM BAD_STYLES ; do
        CURRENT_PROMPT_TEXT_NUM=$((CURRENT_PROMPT_TEXT_NUM + 1))
    done
fi

export CURRENT_PROMPT_COLOR_NUM
export CURRENT_PROMPT_TEXT_NUM
